main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path('', views.IndexView.as_view(), name='default_index'),
    path('sex=<slug:sex>', views.index, name='index'),
    path('clothing_type=<slug:clothing_type>', views.index, name='index'),
    path('sex=<slug:sex>/clothing_type=<slug:clothing_type>', views.index, name='index'),

    path('about/', views.About.as_view(), name='about'),
    path('search', views.search, name='search'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models


class ClothingType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ClothingSex(models.Model):
    sex = models.CharField(max_length=10)

    def __str__(self):
        return self.sex


class ShoppingSite(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.name


class Clothing(models.Model):
    name = models.CharField(max_length=400)
    media = models.JSONField()
    url = models.URLField()
    description = models.TextField(blank=True)
    price = models.IntegerField(default=0)
    color = models.CharField(max_length=100, blank=True)
    parse_date = models.DateTimeField(auto_now_add=True)
    type = models.ForeignKey(ClothingType, on_delete=models.CASCADE)
    site = models.ForeignKey(ShoppingSite, on_delete=models.CASCADE)
    sex = models.ForeignKey(ClothingSex, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

main/views.py
from django.views import generic
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, get_list_or_404, render

from .models import Clothing, ClothingSex, ClothingType

class IndexView(generic.ListView):
    paginate_by = 8
    model = Clothing
    template_name = 'main/index.html'
    context_object_name = 'page_obj'


def index(request, sex=None, clothing_type=None):
    if sex:
        sex_obg = get_object_or_404(ClothingSex, sex=sex)
        if clothing_type:
            clothing_type_obg = get_object_or_404(ClothingType, name=clothing_type)
            clothing = get_list_or_404(Clothing, sex=sex_obg.id, type=clothing_type_obg.id)

        else:
            clothing = get_list_or_404(Clothing, sex=sex_obg.id)

    else:
        clothing_type_obg = get_object_or_404(ClothingType, name=clothing_type)
        clothing = get_list_or_404(Clothing, type=clothing_type_obg.id)

    paginate_by = 8
    paginator = Paginator(clothing, paginate_by)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'main/index.html', {
        'page_obj': page_obj,
    })


class About(generic.ListView):
    model = Clothing
    template_name = 'main/about.html'


def search(request):
    query = request.GET.get('q')
    clothing = Clothing.objects.filter(name__icontains=query)

    paginate_by = 8
    paginator = Paginator(clothing, paginate_by)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'main/index.html',
        {
            'page_obj': page_obj,
            'query': query,
        }
    )

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
            <!-- <h1 class="display-4">All Products</h1> -->
            <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
        </div>
    </div>

    <div class="container">
        <div class="row">
            
        </div>
    </div>
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/templatemo.css' %}">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        <title>{% block title %}ClothesParser{% endblock title %}</title>
        {% block head %}{% endblock head %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand h2 align-self-center" href="{% url 'main:default_index' %}">ClothesParser</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:default_index' %}">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'main:index' sex='man' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Man
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='man' clothing_type='clothing' %}">Clothing</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='man' clothing_type='shoes' %}">Shoes</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='man' clothing_type='accessories' %}">Accessories</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'main:index' sex='woman' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Women
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='woman' clothing_type='clothing' %}">Clothing</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='woman' clothing_type='shoes' %}">Shoes</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='woman' clothing_type='accessories' %}">Accessories</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'main:index' sex='unisex' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Unisex
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='unisex' clothing_type='clothing' %}">Clothing</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='unisex' clothing_type='shoes' %}">Shoes</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:index' sex='unisex' clothing_type='accessories' %}">Accessories</a></li>
                            </ul>
                        </li>
                        
                        <a class="nav-link" href="{% url 'main:about' %}">About</a>
                    </ul>
                    <form class="d-flex" action="/main/search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ query }}">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

        <main>
            {% block content %}

            {% endblock %}
        </main>

        <footer class="text-muted">
        <div class="container">
            <p class="float-right">
            <a href="#">Back to top</a>
            </p>
        </footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/index.css' %}">
{% endblock head %}

{% block content %}
    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
            <h1 class="display-4">All Products</h1>
            <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% for clothing_element in page_obj %}
            <div class="col-md-3" style="margin-bottom: 10px; padding: 0px 5px;">
                <div class="card">
                    {% for media in clothing_element.media %}
                        <div style="background: #020202 url({{ media }}); background-size: cover; background-position: center; background-repeat: no-repeat; width: 100%; height: 250px;"></div>
                    {% endfor %}
                    <div class="card-body">
                        <h5 class="card-title">{{ clothing_element.name }} - <strong>${{ clothing_element.price }}</strong></h5>
                        <p class="card-text text-muted">{{ clothing_element.type }}</p>
                        <p class="card-text">{{ clothing_element.description }}</p>
                        {% if clothing_element.color != "" %}
                            <p class="card-text">Color: {{ clothing_element.color }}</p>
                        {% endif %}
                        <p class="card-text">Parse date: {{ clothing_element.parse_date }}</p>
                        <p class="card-text">From: {{ clothing_element.site }}</p>
                        <a href="{{ clothing_element.url }}" class="btn btn-primary">Go to the product</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        {% if query %}
                            <a href="?q={{ query }}&page=1">&laquo; first</a>
                            <a href="?q={{ query }}&page={{ page_obj.previous_page_number }}">previous</a>
                        {% else %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        {% if query %}
                            <a href="?q={{ query }}&page={{ page_obj.next_page_number }}">next</a>
                            <a href="?q={{ query }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% else %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}